import React from 'react';
import LoginForm from '@/features/authentication/components/LoginForm';
import Link from 'next/link';
import { isMobile } from '@/utils/device';

export const metadata = {
	title: 'Login',
	description: 'Generated by Next.js'
};

const LoginPage = () => {
	const isMobileDevice = isMobile();

	return (
		<div className="text-[#333333]">
			<LoginForm />
			{/* <p className="mt-8 mb-2 text-sm text-center">
				אין לך חשבון? <Link href="/register">יצירת חשבון חדש</Link>
			</p> */}
			<p className="mt-8 text-sm text-center">
				מתקשה בכניסה?{' '}
				<Link href={`${isMobileDevice ? 'tel:0543034727' : 'mailto:twitoorel1@gmail.com'}`} className="font-bold underline underline-black">
					נא ליצור קשר
				</Link>
			</p>
		</div>
	);
};

export default LoginPage;
